In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [12]:
dataset=pd.read_csv('C:\\Users\Admin\Desktop\\RestaurantReviews.tsv',sep='\t')

In [13]:
dataset.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [15]:
dataset['Review'][0]

'Wow... Loved this place.'

In [30]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [51]:
corpus=[]
for i in range(0,1000):
    review=re.sub('[^a-zA-Z]',' ' ,dataset['Review'][i])
    review=review.lower()
    review=review.split()
    pst=PorterStemmer()
    review=[pst.stem(words) for words in review if not words in stopwords.words('English')]
    review=' '.join(review)
    review
    corpus.append(review)

In [60]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [86]:
X=cv.fit_transform(corpus).toarray()

In [87]:
X.shape

(1000, 1565)

In [88]:
y=dataset.iloc[:,1].values

In [89]:
y.shape

(1000,)

In [90]:
from sklearn.model_selection import train_test_split

In [104]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.10, random_state=10)

In [105]:
    X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [126]:
from sklearn.linear_model import LogisticRegression

In [127]:
classifier= LogisticRegression()

In [128]:
classifier.fit(X_train,y_train)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [129]:
ypred=classifier.predict(X_test)

In [130]:
ypred

array([1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0], dtype=int64)

In [131]:
from sklearn.metrics import accuracy_score

In [132]:
accuracy_score(y_test,ypred)*100

74.0

In [133]:
from sklearn.metrics import confusion_matrix

In [134]:
confusion_matrix(y_test,ypred)

array([[38, 11],
       [15, 36]], dtype=int64)